# List of selected font families

# System specific, this one is for Met Office VLD

fontNames = [
    "AR PL UKai CN",
    "AR PL UMing CN",
    "Abyssinica SIL",
    "Andale Mono",
    "AnjaliOldLipi",
    "Arial",
    "Arial Black",
    "BPG Chveulebrivi GPL&GNU",
    "BPG Courier GPL&GNU",
    "BPG Glaho GPL&GNU",
    "C059",
    "Caladea",
    "Cantarell",
    "Carlito",
    "Comic Sans MS",
    "Courier New",
    "David CLM",
    "DejaVu Sans",
    "DejaVu Sans Mono",
    "DejaVu Serif",
    "Dyuthi",
    "Frank Ruehl CLM",
    "FreeMono",
    "FreeSans",
    "FreeSerif",
    "Garuda",
    "Georgia",
    "Gubbi",
    "Hadasim CLM",
    "IPAGothic",
    "IPAMincho",
    "IPAPGothic",
    "IPAPMincho",
    "Impact",
    "Jomolhari",
    "KacstScreen",
    "KacstTitle",
    "KacstTitleL",
    "Kalyani",
    "Keter YG",
    "Khmer OS",
    "Khmer OS Siemreap",
    "Khmer OS System",
    "Kinnari",
    "Liberation Mono",
    "Liberation Sans",
    "Liberation Sans Narrow",
    "Liberation Serif",
    "Lohit Assamese",
    "Lohit Devanagari",
    "Lohit Gujarati",
    "Lohit Kannada",
    "Lohit Marathi",
    "Lohit Punjabi",
    "Lohit Tamil",
    "Loma",
    "Meera",
    "Miriam CLM",
    "Miriam Mono CLM",
    "Nafees Web Naskh",
    "Nanum Brush Script",
    "Nanum Pen Script",
    "NanumGothic",
    "NanumMyeongjo",
    "Navilu",
    "Nimbus Mono PS",
    "Nimbus Roman",
    "Nimbus Sans",
    "Nimbus Sans Narrow",
    "Norasi",
    "Noto Sans",
    "Noto Sans Devanagari",
    "Noto Sans Khmer",
    "Noto Sans Tamil",
    "Noto Sans UI",
    "Noto Serif",
    "Noto Serif Lao",
    "Nuosu SIL",
    "Open Sans",
    "OpenSymbol",
    "Overpass",
    "P052",
    "PT Sans",
    "PT Sans Narrow",
    "Padauk",
    "PakType Naqsh",
    "Pothana2000",
    "Purisa",
    "Rachana",
    "RaghuMalayalam",
    "STIX",
    "STIXGeneral",
    "Saab",
    "Sawasdee",
    "Simple CLM",
    "Stam Ashkenaz CLM",
    "Stone Sans ITC TT",
    "Stone Sans Sem ITC TT",
    "Stone Serif ITC TT",
    "Stone Serif Sem ITC TT",
    "Suruma",
    "Tahoma",
    "Tibetan Machine Uni",
    "Times New Roman",
    "Tlwg Typist",
    "Trebuchet MS",
    "URW Bookman",
    "URW Gothic",
    "Umpush",
    "Unikurd Web",
    "VL Gothic",
    "VL PGothic",
    "Vemana2000",
    "Verdana",
    "Waree",
    "WenQuanYi Micro Hei",
    "WenQuanYi Zen Hei",
    "Z003",
    "cmb10",
    "cmr10",
    "cmtt10",
    "eufm10",
    "kacstPen",
]

fontScales = {"Nanum Brush Script": 1.5, "Nanum Pen Script": 1.5}
