# List of selected font families

# System specific, this one is for Met Office Azure VDI

fontNames = [
    "C059",
    "Caladea",
    "Cantarell",
    "Carlito",
    # "D050000L",
    "DejaVu Math TeX Gyre",
    "DejaVu Sans",
    "DejaVu Sans Mono",
    "DejaVu Serif",
    # "Droid Arabic Kufi",
    "Droid Sans",
    # "Droid Sans Armenian",
    # "Droid Sans Devanagari",
    # "Droid Sans Ethiopic",
    # "Droid Sans Fallback",
    # "Droid Sans Georgian",
    # "Droid Sans Hebrew",
    # "Droid Sans Japanese",
    # "Droid Sans Tamil",
    # "Droid Sans Thai",
    "FreeMono",
    "FreeSans",
    "FreeSerif",
    "Inconsolata",
    "Liberation Mono",
    "Liberation Sans",
    "Liberation Serif",
    "Nimbus Mono PS",
    "Nimbus Roman",
    "Nimbus Sans",
    "Nimbus Sans Narrow",
    #    "Noto Emoji",
    "Noto Sans Mono",
    "Noto Serif",
    "Open Sans",
    "OpenSymbol",
    "P052",
    "Source Code Pro",
    "Stone Sans ITC TT",
    "Stone Sans Sem ITC TT",
    "Stone Serif ITC TT",
    "Stone Serif Sem ITC TT",
    "URW Bookman",
    "URW Gothic",
    "Ubuntu",
    "Ubuntu Condensed",
    "Ubuntu Mono",
    #    "Weather",
    "Z003",
]

# fontScales = {"Nanum Brush Script": 1.5, "Nanum Pen Script": 1.5}
