# Constants for tyrImage module

# List from list_fonts.py
available_fonts = [
    "C059",
    "Caladea",
    "Cantarell",
    "Carlito",
    "D050000L",
    "DejaVu Math TeX Gyre",
    "DejaVu Sans",
    "DejaVu Sans Mono",
    "DejaVu Serif",
    "Droid Sans",
    "FreeMono",
    "FreeSans",
    "FreeSerif",
    "Inconsolata",
    "Liberation Mono",
    "Liberation Sans",
    "Liberation Serif",
    "Nimbus Mono PS",
    "Nimbus Roman",
    "Nimbus Sans",
    "Nimbus Sans Narrow",
    "Noto Sans Mono",
    "Noto Serif",
    # "Open Sans",
    "P052",
    "Source Code Pro",
    "Stone Sans ITC TT",
    "Stone Sans Sem ITC TT",
    "Stone Serif ITC TT",
    "Stone Serif Sem ITC TT",
    "URW Bookman",
    "URW Gothic",
    "Ubuntu",
    "Ubuntu Condensed",
    "Ubuntu Mono",
    "Z003",
]

months = (
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
)
